spring:
  application:
    name: dslist
  profiles:
    active: "${APP_PROFILE:dev}"
  jpa:
    open-in-view: false

cors:
  origins: "*"
  methods: GET, PUT, POST, DELETE, OPTIONS

server:
  error:
    include-stacktrace: never
