spring:
    datasource:
      url: jdbc:postgresql://localhost:5433/dslist
      username: postgres
      password: 1234567

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      properties:
        jakarta:
          persistence:
            schema-generation:
              create-source: metadata
              scripts:
                action: create
                //create-target: create.sql
        hibernate:
          hbm2dll:
            delimiter:
          jdbc:
            lob:
              non_contextual_creation: true
          dll-auto: none